# Generated by Django 5.1.7 on 2025-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_image_journal_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
